### ISSUE TITLE
关于训练出现的报错

### ISSUE THREAD

**Issue by Hsuan2021** [DEVILENMO/Unsupervised-Defect-Detection-Project-Based-on-VAE-GAN-Architecture#3]
您好，我用的图片数据是512*512的单通道图片，在训练过程中出现了以下报错信息，
```
UserWarning: Using a target size (torch.Size([10])) that is different to the input size (torch.Size([5])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)
Traceback (most recent call last):
  File "Unsupervised-Defect-Detection-Project-Based-on-VAE-GAN-Architecture-master\VAE_GAN_train.py", line 57, in <module>
    model.train(train_epochs, 5)
  File "Unsupervised-Defect-Detection-Project-Based-on-VAE-GAN-Architecture-master\GAN.py", line 264, in train
    loss_G_adv = self.criterion_GAN(self.discriminator(y), self.real_labels) + \
  File "anaconda3\envs\tensorflow\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "anaconda3\envs\tensorflow\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "anaconda3\envs\tensorflow\lib\site-packages\torch\nn\modules\loss.py", line 535, in forward
    return F.mse_loss(input, target, reduction=self.reduction)
  File "anaconda3\envs\tensorflow\lib\site-packages\torch\nn\functional.py", line 3365, in mse_loss
    expanded_input, expanded_target = torch.broadcast_tensors(input, target)
  File "anaconda3\envs\tensorflow\lib\site-packages\torch\functional.py", line 76, in broadcast_tensors
    return _VF.broadcast_tensors(tensors)  # type: ignore[attr-defined]
RuntimeError: The size of tensor a (5) must match the size of tensor b (10) at non-singleton dimension 0
```
请问应该如何解决呢？谢谢！

**Comment by DEVILENMO** [comment]
请提供更多的信息，将loss_G_adv = self.criterion_GAN(self.discriminator(y), self.real_labels)中self.discriminator(y)以及self.real_labels的shape打印出来看一下

**Comment by DEVILENMO** [comment]
这里说的是尺寸不对，self.discriminator(y)这里输出的batch_size好像变成5了，建议逐步追踪一下张量尺寸调试一下。如果你解决不了的话可以把你的训练集发给我看一下的话我可以确定一下是不是我代码的问题，我们当时训练没问题来着。

**Comment by Jingyang727** [comment]
> 这里说的是尺寸不对，self.discriminator(y)这里输出的batch_size好像变成5了，建议逐步追踪一下张量尺寸调试一下。如果你解决不了的话可以把你的训练集发给我看一下的话我可以确定一下是不是我代码的问题，我们当时训练没问题来着。

其实有个小bug，你的训练集数量必须是你的batch size的整数倍，才不会raise 这个error,  @DEVILENMO

**Comment by Jingyang727** [comment]
> > 这里说的是尺寸不对，self.discriminator(y)这里输出的batch_size好像变成5了，建议逐步追踪一下张量尺寸调试一下。如果你解决不了的话可以把你的训练集发给我看一下的话我可以确定一下是不是我代码的问题，我们当时训练没问题来着。
> 
> 其实有个小bug，你的训练集数量必须是你的batch size的整数倍，才不会raise 这个error, @DEVILENMO
加一个参数就好
self.train_iterator = DataLoader(self.train_dataset, batch_size=self.batch_size, shuffle=True, drop_last=True)

**Comment by DEVILENMO** [comment]
> > > 这里说的是尺寸不对，self.discriminator(y)这里输出的batch_size好像变成5了，建议逐步追踪一下张量尺寸调试一下。如果你解决不了的话可以把你的训练集发给我看一下的话我可以确定一下是不是我代码的问题，我们当时训练没问题来着。
> > 
> > 
> > 其实有个小bug，你的训练集数量必须是你的batch size的整数倍，才不会raise 这个error, @DEVILENMO
> > 加一个参数就好
> > self.train_iterator = DataLoader(self.train_dataset, batch_size=self.batch_size, shuffle=True, drop_last=True)

哦哦确实，写的时候没注意到，这就改一下，感谢指出

**Comment by DEVILENMO** [comment]
> > > > 这里说的是尺寸不对，self.discriminator(y)这里输出的batch_size好像变成5了，建议逐步追踪一下张量尺寸调试一下。如果你解决不了的话可以把你的训练集发给我看一下的话我可以确定一下是不是我代码的问题，我们当时训练没问题来着。
> > > 
> > > 
> > > 其实有个小bug，你的训练集数量必须是你的batch size的整数倍，才不会raise 这个error, @DEVILENMO
> > > 加一个参数就好
> > > self.train_iterator = DataLoader(self.train_dataset, batch_size=self.batch_size, shuffle=True, drop_last=True)
> 
> 哦哦确实，写的时候没注意到，这就改一下，感谢指出

@Lemon-33
